### ISSUE TITLE
Another npm start issue

### ISSUE THREAD

**Issue by LoZio** [tejado/telegram-nearby-map#21]
Vanilla Ubuntu 20.04 srv full patched here. Stuck on trying to start as other users, with a different problem.
Node v10.19.0
npm 6.14.4

```

> npm run buildParcel && npm run startServer
> telegram-nearby-map@ buildParcel /opt/telegram-nearby-map
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

/opt/telegram-nearby-map/node_modules/@parcel/core/lib/Parcel.js:149
  #requestTracker
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/opt/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/opt/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/opt/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/telegram-nearby-map/node_modules/@parcel/core/lib/index.js:81:39)
/opt/telegram-nearby-map/node_modules/@parcel/logger/lib/Logger.js:41
  #logEmitter
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/opt/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/opt/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _logger (/opt/telegram-nearby-map/node_modules/parcel/lib/cli.js:54:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telegram-nearby-map@ buildParcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-08T07_42_41_772Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telegram-nearby-map@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-08T07_42_41_780Z-debug.log

```

Any idea on how to fix?
Thanks

**Comment by qbno1** [comment]
same problem.... same setup ...

**Comment by wtf-is-github** [comment]
https://stackoverflow.com/questions/68801380/parcel-js-cant-run-same-project-on-ubuntu 

1. update node.js
2. delete node_modules
3. `npm i` 
4. `npm start`

**Comment by LoZio** [comment]
> https://stackoverflow.com/questions/68801380/parcel-js-cant-run-same-project-on-ubuntu
> 
> 1. update node.js
> 2. delete node_modules
> 3. `npm i`
> 4. `npm start`

Thanks @wtf-is-github , I just downloaded the pre-built up-to-date binaries from https://nodejs.org/it/download/ and it went smooth. It was a problem with the bundled node version in Debian.
