### ISSUE TITLE
npm start [ERROR]

### ISSUE THREAD

**Issue by xxxxora** [tejado/telegram-nearby-map#60]
(Quick warning that I'm just a lazy lamer, pls dont bully me.)

Desktop\telegram-nearby-map-main>npm start

> telegram-nearby-map@ start Desktop\telegram-nearby-map-main
> npm run buildParcel && npm run startServer

> telegram-nearby-map@ buildParcel Desktop\telegram-nearby-map-main
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

Desktop\telegram-nearby-map-main\node_modules\@parcel\watcher\index.js:32
  if (err?.code !== 'MODULE_NOT_FOUND') {
          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> Desktop\telegram-nearby-map-main\node_modules\@parcel\fs\lib\index.js:7:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telegram-nearby-map@ buildParcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telegram-nearby-map@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!

**Comment by lillois59** [comment]
npm install before all bro.
