### ISSUE TITLE
Doesnt work: SyntaxError

### ISSUE THREAD

**Issue by keydon3** [tejado/telegram-nearby-map#7]
Hello. Trying to start, but i get syntax error for both npm ci and npm install.

```
/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/Parcel.js:149
  #requestTracker
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/index.js:81:39)
/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/logger/lib/Logger.js:41
  #logEmitter
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _logger (/home/ubuntu/repos/telegram-nearby-map/node_modules/parcel/lib/cli.js:54:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-nearby-map@ buildParcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Full output:
```
ubuntu@test-container:~/repos/telegram-nearby-map$ git config --get remote.origin.url
https://github.com/tejado/telegram-nearby-map.git
ubuntu@test-container:~/repos/telegram-nearby-map$ LANG=en_US.UTF-8 git checkout main && git pull
M       package-lock.json
Already on 'main'
Your branch is up to date with 'origin/main'.
Уже обновлено.
ubuntu@test-container:~/repos/telegram-nearby-map$ LC_ALL=en_US.UTF-8 npm ci
npm WARN prepare removing existing node_modules/ before installation

> tdl-tdlib-addon@1.0.1 install /home/ubuntu/repos/telegram-nearby-map/node_modules/tdl-tdlib-addon
> node-gyp rebuild

make: Entering directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/tdl-tdlib-addon/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/td/td.o
  SOLINK_MODULE(target) Release/obj.target/td.node
  COPY Release/td.node
make: Leaving directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/tdl-tdlib-addon/build'

> msgpackr-extract@1.0.15 install /home/ubuntu/repos/telegram-nearby-map/node_modules/msgpackr-extract
> node-gyp-build

make: Entering directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/msgpackr-extract/build'
  CXX(target) Release/obj.target/msgpackr-extract/src/extract.o
../src/extract.cpp: In member function ‘v8::Local<v8::Value> Extractor::extractStrings(int, int, uint8_t*)’:
../src/extract.cpp:161:36: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
  161 |    array->Set(context, i, target[i]);
      |                                    ^
In file included from ../src/extract.cpp:8:
/usr/include/nodejs/deps/v8/include/v8.h:3252:37: note: declared here
 3252 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
In file included from ../src/extract.cpp:9:
../src/extract.cpp: At global scope:
/usr/include/nodejs/src/node.h:593:51: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_context_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*)’} [-Wcast-function-type]
  593 |       (node::addon_context_register_func) (regfunc),                  \
      |                                                   ^
/usr/include/nodejs/src/node.h:611:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’
  611 |   NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/extract.cpp:269:1: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’
  269 | NODE_MODULE_CONTEXT_AWARE(extractor, initializeModule);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/extract.cpp:8:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/msgpackr-extract.node
  COPY Release/msgpackr-extract.node
make: Leaving directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/msgpackr-extract/build'

> lmdb-store@1.6.13 install /home/ubuntu/repos/telegram-nearby-map/node_modules/lmdb-store
> node-gyp-build

make: Entering directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/lmdb-store/build'
  CXX(target) Release/obj.target/lmdb/src/node-lmdb.o
  CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/chacha8.o
  CC(target) Release/obj.target/lmdb/dependencies/lz4/lib/lz4.o
  CXX(target) Release/obj.target/lmdb/src/env.o
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::open(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:559:55: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
  559 |     rc = mdb_env_open(ew->env, *String::Utf8Value(path), flags, 0664);
      |                                                       ^
In file included from /usr/include/nodejs/deps/v8/include/v8.h:26,
                 from ../src/node-lmdb.h:29,
                 from ../src/env.cpp:25:
/usr/include/nodejs/deps/v8/include/v8.h:2892:28: note: declared here
 2892 |                   explicit Utf8Value(Local<v8::Value> obj));
      |                            ^~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
  CXX(target) Release/obj.target/lmdb/src/compression.o
  CXX(target) Release/obj.target/lmdb/src/ordered-binary.o
../src/ordered-binary.cpp: In function ‘size_t valueToKey(const v8::Local<v8::Value>&, uint8_t*, size_t, bool, bool)’:
../src/ordered-binary.cpp:68:18: warning: ‘number’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   68 |         uint64_t asInt = *((uint64_t*) &number);
      |                  ^~~~~
  CXX(target) Release/obj.target/lmdb/src/misc.o
  CXX(target) Release/obj.target/lmdb/src/txn.o
  CXX(target) Release/obj.target/lmdb/src/dbi.o
../src/dbi.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE DbiWrap::ctor(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/dbi.cpp:171:74: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
  171 |     rc = mdb_dbi_open(txn, nameIsNull ? nullptr : *String::Utf8Value(name), flags, &dbi);
      |                                                                          ^
In file included from /usr/include/nodejs/deps/v8/include/v8.h:26,
                 from ../src/node-lmdb.h:29,
                 from ../src/dbi.cpp:25:
/usr/include/nodejs/deps/v8/include/v8.h:2892:28: note: declared here
 2892 |                   explicit Utf8Value(Local<v8::Value> obj));
      |                            ^~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
  CXX(target) Release/obj.target/lmdb/src/cursor.o
  CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
  SOLINK_MODULE(target) Release/obj.target/lmdb.node
  COPY Release/lmdb.node
make: Leaving directory '/home/ubuntu/repos/telegram-nearby-map/node_modules/lmdb-store/build'

> @parcel/watcher@2.0.2 install /home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/watcher
> node-gyp-build


> core-js@3.19.1 postinstall /home/ubuntu/repos/telegram-nearby-map/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://paypal.me/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 769 packages in 20.561s
ubuntu@test-container:~/repos/telegram-nearby-map$ npm start

> telegram-nearby-map@ start /home/ubuntu/repos/telegram-nearby-map
> npm run buildParcel && npm run startServer


> telegram-nearby-map@ buildParcel /home/ubuntu/repos/telegram-nearby-map
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/Parcel.js:149
  #requestTracker
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/index.js:81:39)
/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/logger/lib/Logger.js:41
  #logEmitter
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _logger (/home/ubuntu/repos/telegram-nearby-map/node_modules/parcel/lib/cli.js:54:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-nearby-map@ buildParcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-11-14T18_06_23_130Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-nearby-map@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-11-14T18_06_23_145Z-debug.log
ubuntu@test-container:~/repos/telegram-nearby-map$ cat /home/ubuntu/.npm/_logs/2021-11-14T18_06_23_130Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'buildParcel' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuildParcel', 'buildParcel', 'postbuildParcel' ]
5 info lifecycle telegram-nearby-map@~prebuildParcel: telegram-nearby-map@
6 info lifecycle telegram-nearby-map@~buildParcel: telegram-nearby-map@
7 verbose lifecycle telegram-nearby-map@~buildParcel: unsafe-perm in lifecycle true
8 verbose lifecycle telegram-nearby-map@~buildParcel: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/repos/telegram-nearby-map/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/repos/telegram-nearby-map/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle telegram-nearby-map@~buildParcel: CWD: /home/ubuntu/repos/telegram-nearby-map
10 silly lifecycle telegram-nearby-map@~buildParcel: Args: [ '-c',
10 silly lifecycle   'parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/' ]
11 silly lifecycle telegram-nearby-map@~buildParcel: Returned: code: 1  signal: null
12 info lifecycle telegram-nearby-map@~buildParcel: Failed to exec buildParcel script
13 verbose stack Error: telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid telegram-nearby-map@
15 verbose cwd /home/ubuntu/repos/telegram-nearby-map
16 verbose Linux 5.4.0-90-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "buildParcel"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
22 error Exit status 1
23 error Failed at the telegram-nearby-map@ buildParcel script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
ubuntu@test-container:~/repos/telegram-nearby-map$ cat /home/ubuntu/.npm/_logs/2021-11-14T18_06_23_145Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle telegram-nearby-map@~prestart: telegram-nearby-map@
6 info lifecycle telegram-nearby-map@~start: telegram-nearby-map@
7 verbose lifecycle telegram-nearby-map@~start: unsafe-perm in lifecycle true
8 verbose lifecycle telegram-nearby-map@~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/repos/telegram-nearby-map/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle telegram-nearby-map@~start: CWD: /home/ubuntu/repos/telegram-nearby-map
10 silly lifecycle telegram-nearby-map@~start: Args: [ '-c', 'npm run buildParcel && npm run startServer' ]
11 silly lifecycle telegram-nearby-map@~start: Returned: code: 1  signal: null
12 info lifecycle telegram-nearby-map@~start: Failed to exec start script
13 verbose stack Error: telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid telegram-nearby-map@
15 verbose cwd /home/ubuntu/repos/telegram-nearby-map
16 verbose Linux 5.4.0-90-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
22 error Exit status 1
23 error Failed at the telegram-nearby-map@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

ubuntu@test-container:~/repos/telegram-nearby-map$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
audited 769 packages in 2.551s

145 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

ubuntu@test-container:~/repos/telegram-nearby-map$ npm start

> telegram-nearby-map@ start /home/ubuntu/repos/telegram-nearby-map
> npm run buildParcel && npm run startServer


> telegram-nearby-map@ buildParcel /home/ubuntu/repos/telegram-nearby-map
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/Parcel.js:149
  #requestTracker
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/core/lib/index.js:81:39)
/home/ubuntu/repos/telegram-nearby-map/node_modules/@parcel/logger/lib/Logger.js:41
  #logEmitter
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/repos/telegram-nearby-map/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _logger (/home/ubuntu/repos/telegram-nearby-map/node_modules/parcel/lib/cli.js:54:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ buildParcel: `parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-nearby-map@ buildParcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-11-14T18_09_43_654Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-nearby-map@ start: `npm run buildParcel && npm run startServer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-nearby-map@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-11-14T18_09_43_669Z-debug.log

ubuntu@test-container:~/repos/telegram-nearby-map$ cat config.js 
var config = {} 


// your telegram API credentials
// please go to https://my.telegram.org to create your API credentials
config.telegramApiId = '********';
config.telegramApiHash = '********************************';


// server settings
config.hostname = '127.0.0.1';
config.port = 3000;


module.exports = config;
```

**Comment by tejado** [comment]
Can you please update to a newer node version (e.g. 14 or 16) and try again? Thanks.

**Comment by keydon3** [comment]
Thank you! All works! My bad.

**Comment by tejado** [comment]
I'm glad that it is now working. Thanks for the info! :)
